package de.wonderworld.plugins.selfmadeEssentials.localization;

public class LAN_EN {
    public static final String NOT_INSTANCEOF_PLAYER = "&cThis way this command can only be used ingame.";
    public static final String NOT_VALID_PLAYER_NAME_FORMAT = "&cThe name &f%s &cis not a valid playername.";
    public static final String SOCIAL_SPY_IS_NOW_ON = "&6Your socialspy state is now &aon&6.";
    public static final String SOCIAL_SPY_IS_NOW_OFF = "&6Your socialspy state is now &coff&6.";
    public static final String PLAYER_NOT_FOUND_FORMAT = "&cThe player &f%s &cwasn't found.";
    public static final String MOB_NOT_FOUND_FORMAT = "&cThe mob &f%s &cwasn't found.";
    public static final String FLY_MODE_ON = "&6Your fly mode is now &aon&6.";
    public static final String PLAYER_KILLED_HIMSELF_FORMAT ="&c%s &6committed suicide.";
    public static final String FLY_MODE_OFF = "&6Your fly mode is now &coff&6.";
    public static final String WARP_SET_FORMAT = "&aThe warp &f%s &ahas been set to your current location.";
    public static final String WARP_REMOVED_FORMAT = "&aThe warp &f%s &ahas been removed.";
    public static final String WARP_DOES_NOT_EXIST_FORMAT = "&cThe warp &f%s &cdoes not exists.";
    public static final String ARGUMENT_HAS_TO_BE_INTEGER_FORMAT = "&cThe argument &f%s &chas to be a number.";
    public static final String TREETYPE_NOT_FOUND_FORMAT = "&cThe treetype &f%s &cwasn't found.";
    public static final String COMMAND_NOT_FOUND_FORMAT = "&cThe command &f%s &cwasn't found.";
    public static final String AVAILABLE_COMMAND_STAGES = "&cThe command stage you entered is not available. Available stages are: &astable &ebeta &calpha.";
    public static final String COMMAND_CHANGED_TO_ALPHA_FORMAT = "&6The command stage of &f%s &6has been set to &calpha.";
    public static final String COMMAND_CHANGED_TO_BETA_FORMAT = "&6The command stage of &f%s &6has been set to &ebeta.";
    public static final String COMMAND_CHANGED_TO_STABLE_FORMAT = "&6The command stage of &f%s &6has been set to &astable.";
    public static final String AVAILABLE_TREETYPES_FORMAT = "&6Available tree types are &f%s.";
    public static final String COMMENT_SET = "&aYour comment has been set. Thanks for your help. =)";
    public static final String COMMENT_INTRO = "&6Following comments are already submitted:";
    public static final String VANISH_ACTIVE = "&6Your vanish mode is now &aon&6.";
    public static final String VANISH_INACTIVE = "&6Your vanish mode is now &coff&6.";
    public static final String PLAYER_JOINED_VANISH_FORMAT = "&6The player &f%s &6joined vanish.";
    public static final String PLAYER_FAKE_QUIT_FORMAT = "&e%s left the game";
    public static final String PLAYER_FAKE_JOIN_FORMAT = "&e%s joined the game";
    public static final String PLAYER_ENTERED_VANISH = "&6The player &f%s &centered &6vanish mode.";
    public static final String PLAYER_LEFT_VANISH_FORMAT = "&6The player &f%s &aleft &6vanish mode.";
    public static final String SOCIALSPY_MSG_SENDER_ME = "&6[&a%s&6] => [&ame&6]: &f%s";
    public static final String SOCIALSPY_MSG_ME_SENDER = "&6[&ame&6] => [&a%s&6]: &f%s";
    public static final String SOCIALSPY_MSG_SENDER_RECIEVER = "&8[&a%s&8] => [&a%s&8]: &f%s";
    public static final String WARP_WORLD_NOT_LOADED = "&cThe world this warp is refering to is currently not loaded.";
    public static final String ENTERED_VANISH_VISIBLE = "&6You &acan &6now see players in vanish mode.";
    public static final String LEFT_VANISH_VISIBLE = "&6You &ccan't &6see players in vanish mode anymore.";
    public static final String VANISH_NOT_PERMITTED = "&cYou are not permitted to use this command.";
    public static final String PTIME_EQUAL_TO_SERVER_FORMAT = "&6Your player time is identical to the server time.";
    public static final String PTIME_ABSOLUTE_FORMAT = "&6Your absolute player time is &f%d&6.";
    public static final String PTIME_RELATIVE_BEHIND_FORMAT = "&6Your relative player time is &f%d &6ticks behind the server time.";
    public static final String PTIME_RELATIVE_AHEAD_FORMAT = "&6Your relative player time is &f%d &6ticks ahead the server time.";
    public static final String PTIME_RESET = "&6Your player time has been reset.";
    public static final String PTIME_CONSTANT_FORMAT = "&6Your player time has been set to constantly &f%d &6ticks.";
    public static final String PTIME_NOT_NUMBER_FORMAT = "&cThe argument &f%s &chas to be a number.";
    public static final String PTIME_NOT_BOOLEAN_FORMAT = "&cThe argument &f%s &chas to be &ftrue &6or &ffalse&6.";
    public static final String PTIME_INTRO = "&6The following arguments are allowed:";
    public static final String EFFECT_NOT_FOUND_FORMAT = "&cThe effect &f%s &cwas not found.";
    public static final String EFFECT_GAINED_FORMAT = "&aYou recieved the effect &f%s &a.";
    public static final String VANISH_LIST_INTRO = "&6The following currently online players have the ability to see you:";
    public static final String GAMEMODE_BIGGER_3 = "&cGamemode value has to be less than 4.";
    public static final String GAMEMODE_SET_FORMAT = "&6Your gamemode has been set to &f%s&6.";
    public static final String SUDO_COMMAND_NOT_ALLOWED = "&cYou can't perform messaging commands through sudo.";
    public static final String ARGUMENT_HAS_TO_BE_INTEGER_OR_LESS_ARGUMENTS_FORMAT = "&cThe argument &f%s &chas to be a number or the gamemode is missing.";
    public static final String SPEED_INFO_FORMAT = "&6Your walk speed is &f%s&6 and your fly speed is &f%s&6.";
    public static final String SPEED_WRONG_ARGUMENT_FORMAT = "&cThe argument &f%s &chas to be a number till 100.";
    public static final String SPEED_WALK_FLY_SET_FORMAT = "&6Your walk and fly speed has been set to &f%s&6.";
    public static final String SPEED_FLY_SET_FORMAT = "&6Your fly speed has been set to &f%s&6.";
    public static final String SPEED_WALK_SET_FORMAT = "&6Your walk speed has been set to &f%s&6.";
    public static final String SPEED_RESET = "&6Your walk and fly speed has been reset to &f0.1&6 and &f0.2&6.";
    public static final String GODMODE_IS_NOW_ON = "&6Your godmode is now &aon&6.";
    public static final String GODMODE_IS_NOW_OFF = "&6Your godmode is now &coff&6.";
    public static final String HOME_SET_FORMAT = "&6Your home: &f%s &6has been set.";
    public static final String DELHOME_INFO = "&6Your following homes are able to get deleted:";
    public static final String DELHOME_SUCCESS_FORMAT = "&6Your home &f%s &6has been &adeleted.";
    public static final String HOME_NOT_FOUND_FORMAT = "&cYour home &f%s &cwas not found.";
    public static final String HOME_WORLD_NOT_LOADED = "&cThe world this home is refering to is currently not loaded.";
    public static final String ITEM_MUST_BE_AN_OBJECT = "&6You do not have an item in your hand.";
    public static final String ITEM_REPAIRED = "&6Item &arepaired&6.";
    public static final String NUMBER_EXPECTED_FORMAT = "&cThe argument &f%s&c has to be a number.";
    public static final String PLAYERS_NOT_TELEPORTED_FORMAT = "&6The players &f%s&6 were not teleported because they are not allowed to fly.";
    public static final String UNLIMITED_IS_NOW_ON = "Unlimited is now active.";
    public static final String UNLIMITED_IS_NOW_OFF = "Unlimited is now inactive.";
    public static final String QUICK_RESPONSE_NOT_AVAILABLE = "&cThere is no player who wrote to you. &6Start a conversation with \"&f/msg&6\".";
}
