package de.wonderworld.plugins.selfmadeEssentials.localization;

public class LAN_DE {
    public static final String NOT_INSTANCEOF_PLAYER = "&cDer Befehl kann so nur im Spiel genutzt werden.";
    public static final String NOT_VALID_PLAYER_NAME_FORMAT = "&cDer Name &f%s &cist kein gültiger Spielername.";
    public static final String SOCIAL_SPY_IS_NOW_ON = "&6Dein SocialSpy Status ist nun &aan&6.";
    public static final String SOCIAL_SPY_IS_NOW_OFF = "&6Dein SocialSpy Status ist nun &caus&6.";
    public static final String PLAYER_NOT_FOUND_FORMAT = "&cDer Spieler &f%s &cwurde nicht gefunden.";
    public static final String MOB_NOT_FOUND_FORMAT = "&cDer Mob &f%s &cwurde nicht gefunden.";
    public static final String FLY_MODE_ON = "&6Dein Flugmodus ist nun &aan&6.";
    public static final String PLAYER_KILLED_HIMSELF_FORMAT ="&c%s &6begang Selbstmord.";
    public static final String FLY_MODE_OFF = "&6Dein Flugmodus ist nun &caus&6.";
    public static final String WARP_SET_FORMAT = "&aDer Warp &f%s &awurde auf deine aktuelle Position gesetzt.";
    public static final String WARP_REMOVED_FORMAT = "&aDer Warp &f%s &awurde entfernt.";
    public static final String WARP_DOES_NOT_EXIST_FORMAT = "&cDer Warp &f%s &cexistiert nicht.";
    public static final String ARGUMENT_HAS_TO_BE_INTEGER_FORMAT = "&cDas Argument &f%s &cmuss eine Zahl sein.";
    public static final String TREETYPE_NOT_FOUND_FORMAT = "&cDer Baumtyp &f%s &cwurde nicht gefunden.";
    public static final String COMMAND_NOT_FOUND_FORMAT = "&cDer Befehl &f%s &cwurde nicht gefunden.";
    public static final String AVAILABLE_COMMAND_STAGES = "&cDie angegebene Befehlsphase ist nicht verfügbar. Verfügbare Phasen sind: &astable &ebeta &calpha.";
    public static final String COMMAND_CHANGED_TO_ALPHA_FORMAT = "&6Die Befehlsphase von &f%s &6wurde auf &calpha &6gesetzt.";
    public static final String COMMAND_CHANGED_TO_BETA_FORMAT = "&6Die Befehlsphase von &f%s &6wurde auf &ebeta &6gesetzt.";
    public static final String COMMAND_CHANGED_TO_STABLE_FORMAT = "&6Die Befehlsphase von &f%s &6wurde auf &astable &6gesetzt.";
    public static final String AVAILABLE_TREETYPES_FORMAT = "&6Verfügbare Baumtypen sind: &f%s.";
    public static final String COMMENT_SET = "&aDein Kommentar wurde gesetzt. Danke für deine Unterstützung. =)";
    public static final String COMMENT_INTRO = "&6Folgende Kommentare wurden bereits eingereicht:";
    public static final String VANISH_ACTIVE = "&6Dein Vanish Modus ist nun &aan&6.";
    public static final String VANISH_INACTIVE = "&6Dein Vanish Modus ist nun &caus&6.";
    public static final String PLAYER_JOINED_VANISH_FORMAT = "&6Der Spieler &f%s &6betrat den Server im Vanish Modus.";
    public static final String PLAYER_FAKE_QUIT_FORMAT = "&e%s left the game";
    public static final String PLAYER_FAKE_JOIN_FORMAT = "&e%s joined the game";
    public static final String PLAYER_ENTERED_VANISH = "&6Der Spieler &f%s &6schaltete seinen Vanish Modus &can&6.";
    public static final String PLAYER_LEFT_VANISH_FORMAT = "&6Der Spieler &f%s &6schaltete seinen Vanish Modus &aaus&6.";
    public static final String SOCIALSPY_MSG_SENDER_ME = "&6[&a%s&6] => [&aIch&6]: &f%s";
    public static final String SOCIALSPY_MSG_ME_SENDER = "&6[&aIch&6] => [&a%s&6]: &f%s";
    public static final String SOCIALSPY_MSG_SENDER_RECIEVER = "&8[&a%s&8] => [&a%s&8]: &f%s";
    public static final String WARP_WORLD_NOT_LOADED = "&cDie Welt, zu der dieser Warp führt, ist gerade nicht geladen.";
    public static final String ENTERED_VANISH_VISIBLE = "&6Du kannst nun Spieler im Vanish Modus sehen.";
    public static final String LEFT_VANISH_VISIBLE = "&6GERMAN: You &ccan't &6see players in vanish mode anymore.";
    public static final String VANISH_NOT_PERMITTED = "&cDieser Befehl ist für dich nicht verfügbar.";
    public static final String PTIME_EQUAL_TO_SERVER_FORMAT = "&6Deine Zeit ist identisch mit der des Servers.";
    public static final String PTIME_ABSOLUTE_FORMAT = "&6Deine &fabsolute &6Zeit ist &f%d&6.";
    public static final String PTIME_RELATIVE_BEHIND_FORMAT = "&6Deine &frelative &6Zeit ist &f%d &6Ticks hinter der Server Zeit.";
    public static final String PTIME_RELATIVE_AHEAD_FORMAT = "&6Deine &frelative &6Zeit ist &f%d &6Ticks hinter der Server Zeit.";
    public static final String PTIME_RESET = "&6Deine Zeit wurde auf die Server Zeit zurückgesetzt.";
    public static final String PTIME_CONSTANT_FORMAT = "&6Deine Zeit wurde auf konstante &f%d &6Ticks gesetzt.";
    public static final String PTIME_NOT_NUMBER_FORMAT = "&cDas Argument &f%s &cmuss eine Zahl sein."; //TODO remove String
    public static final String PTIME_NOT_BOOLEAN_FORMAT = "&cDas Argument &f%s &cmuss &ftrue &6,oder &ffalse&6 sein.";
    public static final String PTIME_INTRO = "&6Die folgenden Argumente sind erlaubt:";
    public static final String EFFECT_NOT_FOUND_FORMAT = "&cDer Effekt &f%s &cwurde nicht gefunden.";
    public static final String EFFECT_GAINED_FORMAT = "&aDu hast den Effekt &f%s &aerhalten.";
    public static final String VANISH_LIST_INTRO = "&6Die folgenden Online Spieler können dich sehen:";
    public static final String GAMEMODE_BIGGER_3 = "&cDer Gamemodus Wert muss kleiner als 4 sein.";
    public static final String GAMEMODE_SET_FORMAT = "&6Dein Gamemodus wurde auf &f%s&6gesetzt.";
    public static final String SUDO_COMMAND_NOT_ALLOWED = "&cDu kannst keine Nachrichten Befehle durch sudo nutzen.";
    public static final String ARGUMENT_HAS_TO_BE_INTEGER_OR_LESS_ARGUMENTS_FORMAT = "&cDas Argument &f%s &cmuss eine Zahl sein, oder der Gamemodus fehlt.";
    public static final String SPEED_INFO_FORMAT = "&6Deine Laufgeschwindigkeit ist &f%s&6 und deine Fluggeschwindigkeit ist &f%s&6.";
    public static final String SPEED_WRONG_ARGUMENT_FORMAT = "&cDas Argument &f%s &cmuss eine Zahl bis 100 sein.";
    public static final String SPEED_WALK_FLY_SET_FORMAT = "&6Deine Lauf-/Fluggeschwindigkeit wurde auf &f%s&6 gesetzt.";
    public static final String SPEED_FLY_SET_FORMAT = "&6Deine Fluggeschwindigkeit wurde auf &f%s&6gesetzt.";
    public static final String SPEED_WALK_SET_FORMAT = "&6Deine Laufgeschwindigkeit wurde auf &f%s&6gesetzt.";
    public static final String SPEED_RESET = "&6Deine Lauf-/ und Fluggeschwindigkeit wurde auf &f0.1&6 und &f0.2&6zurückgesetzt.";
    public static final String GODMODE_IS_NOW_ON = "&6Dein Godmodus ist nun &aan&6.";
    public static final String GODMODE_IS_NOW_OFF = "&6Dein Godmodus ist nun &caus&6.";
    public static final String HOME_SET_FORMAT = "&6Dein Homepunkt &f%s &6wurde gesetzt.";
    public static final String DELHOME_INFO = "&6Die folgenden Homepunkte stehen zur Löschung bereit:";
    public static final String DELHOME_SUCCESS_FORMAT = "&6Dein Homepunkt &f%s &6wurde &agelöscht&6.";
    public static final String HOME_NOT_FOUND_FORMAT = "&cDein Homepunkt &f%s &cwurde nicht gefunden.";
    public static final String HOME_WORLD_NOT_LOADED = "&cDie Welt, zu der dieser Homepunkt führt, ist gerade nicht geladen.";
    public static final String ITEM_MUST_BE_AN_OBJECT = "&6Du hast keinen Gegenstand in der Hand.";
    public static final String ITEM_REPAIRED = "&6Gegenstand &arepariert&6.";
    public static final String NUMBER_EXPECTED_FORMAT = "&cDas Argument &f%s&c muss eine Zahl sein.";
    public static final String PLAYERS_NOT_TELEPORTED_FORMAT = "&6Die Spieler &f%s&6 wurden nicht teleportiert, da sie nicht berechtigt sind zu fliegen.";
    public static final String QUICK_RESPONSE_NOT_AVAILABLE = "&cEs hat dir noch kein Spieler geschrieben. &6Beginne eine Konversation mit: \"&f/msg&6\".";
}
